#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    if [[ -z "$BASEURL" ]]; then
        exec 2>&1 \
            s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 1935" \
                s6-setuidgid abc /app/get_iplayer/get_iplayer.cgi -p 1935 --getiplayer /app/get_iplayer/get_iplayer;
    else
        exec 2>&1 \
            s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 1935" \
                s6-setuidgid abc /app/get_iplayer/get_iplayer.cgi -p 1935 -b "$BASEURL" --getiplayer /app/get_iplayer/get_iplayer;
    fi
else
    if [[ -z "$BASEURL" ]]; then
        exec 2>&1 \
            s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 1935" \
                /app/get_iplayer/get_iplayer.cgi -p 1935 --getiplayer /app/get_iplayer/get_iplayer;
    else
        exec 2>&1 \
            s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 1935" \
                /app/get_iplayer/get_iplayer.cgi -p 1935 -b "$BASEURL" --getiplayer /app/get_iplayer/get_iplayer;
    fi
fi
