#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    if [[ ${ENABLEIMPORT,,} == "true" ]]; then
            s6-setuidgid abc /app/get_iplayer/get_iplayer --pvr --quiet 2>&1

        exec 2>&1 \
            s6-setuidgid abc /usr/share/dotnet/dotnet /app/sonarrautoimport/SonarrAutoImport.dll /config/settings.json
    else
        exec 2>&1 \
            s6-setuidgid abc /app/get_iplayer/get_iplayer --pvr --quiet
    fi
else
    if [[ ${ENABLEIMPORT,,} == "true" ]]; then
            /app/get_iplayer/get_iplayer --pvr --quiet 2>&1

        exec 2>&1 \
            /usr/share/dotnet/dotnet /app/sonarrautoimport/SonarrAutoImport.dll /config/settings.json
    else
        exec 2>&1 \
            /app/get_iplayer/get_iplayer --pvr --quiet
    fi
fi
