#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /config/.get_iplayer \
    /config/log/get_iplayer/ \
    /run/get_iplayer-temp

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    lsiown -R abc:abc \
        /config \
        /run/get_iplayer-temp

    if grep -qe ' /downloads ' /proc/mounts; then
        lsiown -R abc:abc \
            /downloads
    fi

    #refresh cache if necessary
    if [[ $INCLUDERADIO == "true" ]]; then
        if [[ ! -f "/config/.get_iplayer/tv.cache" ]] || [[ ! -f "/config/.get_iplayer/radio.cache" ]]; then
            exec \
            s6-setuidgid abc /app/get_iplayer/get_iplayer --refresh --type=all
        fi
    else
        if [[ ! -f "/config/.get_iplayer/tv.cache" ]]; then
            exec \
            s6-setuidgid abc /app/get_iplayer/get_iplayer --refresh --type=tv
        fi
    fi
else
    #refresh cache if necessary
    if [[ $INCLUDERADIO == "true" ]]; then
        if [[ ! -f "/config/.get_iplayer/tv.cache" ]] || [[ ! -f "/config/.get_iplayer/radio.cache" ]]; then
            exec \
            /app/get_iplayer/get_iplayer --refresh --type=all
        fi
    else
        if [[ ! -f "/config/.get_iplayer/tv.cache" ]]; then
            exec \
            /app/get_iplayer/get_iplayer --refresh --type=tv
        fi
    fi
fi
