#!/usr/bin/with-contenv bash

mkdir -p /config/.get_iplayer

# permissions
chown -R abc:abc \
	/app/get_iplayer \
	/config \
	/downloads

#refresh cache if necessary
if [[ $INCLUDERADIO == "true" ]]; then
	if [ ! -f "/config/.get_iplayer/tv.cache" ] | [! -f "/config/.get_iplayer/radio.cache"]; then
		exec \
    		s6-setuidgid abc /app/get_iplayer/get_iplayer --refresh --type=all
	fi
else
	if [ ! -f "/config/.get_iplayer/tv.cache" ]; then
		exec \
    		s6-setuidgid abc /app/get_iplayer/get_iplayer --refresh --type=tv
	fi
fi