#!/usr/bin/with-contenv bash

if [ ! -f "/config/.get_iplayer" ]; then
	mkdir -p /config/.get_iplayer
fi

if [ ! -f "/config/log" ]; then
	mkdir -p /config/log
fi

# permissions
chown -R abc:abc \
	/app/get_iplayer \
	/config \
	/downloads

chmod 644 \
	/etc/logrotate.d/get_iplayer \
	/etc/logrotate.d/get_iplayer_web

#refresh cache if necessary
if [[ $INCLUDERADIO == "true" ]]; then
	if [ ! -f "/config/.get_iplayer/tv.cache" ] || [! -f "/config/.get_iplayer/radio.cache"]; then
		exec \
    		s6-setuidgid abc /app/get_iplayer/get_iplayer --refresh --type=all
	fi
else
	if [ ! -f "/config/.get_iplayer/tv.cache" ]; then
		exec \
    		s6-setuidgid abc /app/get_iplayer/get_iplayer --refresh --type=tv
	fi
fi